Modifications in postinst file

diff --git a/mikro-helper/DEBIAN/postinst b/mikro-helper/DEBIAN/postinst
--- a/mikro-helper/DEBIAN/postinst
+++ b/mikro-helper/DEBIAN/postinst
@@ -7,8 +7,9 @@ if [ "$(id -u)" -ne 0 ]; then
 fi
 
 # Define the installation directory
-INSTALL_DIR="/home/user/mikro-helper/mikro-helper"
+INSTALL_DIR="~/mikro-helper/mikro-helper"
 PROGRAM_PATH="$INSTALL_DIR/mikro-helper.py"
+#CONFIG_FILE="$INSTALL_DIR/conf.ini"
 
 dos2unix "$PROGRAM_PATH"
 
@@ -19,6 +20,22 @@ chmod +x "$PROGRAM_PATH"
 if [ ! -L /usr/local/bin/mikro-helper ]; then
     ln -s "$PROGRAM_PATH" /usr/local/bin/mikro-helper
 fi
+
+
+#if [ -f "$CONFIG_FILE" ]; then
+#    echo "Updating the configuration file with the new path..."
+#    
+#    # Add or update the 'hosts_folder_path' entry in the configuration file
+#    # This uses `sed` to replace the line if it exists, or append it if not
+#    sed -i "s|^hosts_folder_path=.*|hosts_folder_path=$INSTALL_DIR/hosts|" "$CONFIG_FILE" || echo "hosts_folder_path=$INSTALL_DIR/hosts" >> "$CONFIG_FILE"
+#    
+#    # Corrected 'vars_folder_path' entry update
+#    sed -i "s|^vars_folder_path=.*|vars_folder_path=$INSTALL_DIR/vars|" "$CONFIG_FILE" || echo "vars_folder_path=$INSTALL_DIR/vars" >> "$CONFIG_FILE"
+#else
+#    echo "Configuration file not found at $CONFIG_FILE" >&2
+#    exit 1
+#fi
+
 
 echo "Postinst completed"
 
