Update preinst

diff --git a/DEBIAN/preinst b/DEBIAN/preinst
--- a/DEBIAN/preinst
+++ b/DEBIAN/preinst
@@ -1,15 +1,15 @@
 #!/bin/bash
 
-# Define dependencies
-DEPENDENCIES=("python3" "dos2unix" "python3-paramiko" "python3-yaml")
+## Define dependencies
+# DEPENDENCIES=("python3" "dos2unix" "python3-paramiko" "python3-yaml")
 
-# Check if the dependencies are installed
-for dep in "${DEPENDENCIES[@]}"; do
-    if ! dpkg-query -W -f='${Status}' "$dep" 2>/dev/null | grep "install ok installed" > /dev/null; then
-        echo "Dependency $dep is missing. Installing..."
-        apt-get update
-        apt-get install -y "$dep"
-    else
-        echo "Dependency $dep is already installed."
-    fi
-done
+## Check if the dependencies are installed
+#for dep in "${DEPENDENCIES[@]}"; do
+ #   if ! dpkg-query -W -f='${Status}' "$dep" 2>/dev/null | grep "install ok installed" > /dev/null; then
+  #      echo "Dependency $dep is missing. Installing..."
+   #     apt-get update
+    #    apt-get install -y "$dep"
+    #else
+     #   echo "Dependency $dep is already installed."
+    #fi
+#done
